version: 2.1

orbs:
 percy: percy/agent@0.1.2

jobs:
 run_tests:
   parallelism: 3
   steps:
     - attach_workspace:
         at: .
     - run:
         name: install depedencies
         command: |
             npm install
             gem install percy-cli

     - run:
         name: run test
         command: |
           npm run build
           percy snapshot_site

workflows:
 test:
   jobs:
     - run_tests
     - percy/finalize_all:
         requires:
           - run_tests
