version: 2.1

orbs:
 percy: percy/agent@0.1.2

jobs:
 run_tests:
   parallelism: 3

   working_directory: ~/repo
   steps:
     - checkout
     - run :
          name : install depedencies
          command: |
            npm install
            gem install percy-cli

     - run :
         name : run test
         command: |
           npm run build
           percy snapshot_site